### ISSUE TITLE
About the attempts on the few-shot task.

### ISSUE THREAD

**Issue by AI7Xiao** [alibaba/graph-gpt#5]
Thank you very much for your contribution to the code repository.

Currently I am trying to improve the performance of GraphGPT on the few-shot task in terms of dataset, model architecture, and so on.

I heard that you have already tried it on **PCQM4M-v2** dataset, I would like to ask what data processing and experimental details you have performed? (e.g., did you take only a small portion of the PCQM4M-v2 dataset for testing?)

**Comment by zhaoqf123** [comment]
Hey,

Early this year, we have tried few-shot on PCQM4M-v2 dataset with NTP pre-training and `prolonged` Eulerian sequence. However, we didn't see improvements and then gave up.

This could be due to several reasons, for example: a). As stated in https://github.com/alibaba/graph-gpt/issues/3#issuecomment-2451398597, NTP pre-trained is worse than SMTP pre-trained. b). The few-shot samples are not similar to the target sample, and thus bring little benefits to the prediction of the target sample (We only tried randomly sampled few-shot samples.)

So, if you tried with bi-directional transformer architecture as SMTP, and retrieve similar molecules as the target to do the few-shot, the results could be improved. (If I remembered correctly, AlphaFold did retrieve similar proteins as the target to improve the structure prediction.)

Currently, we are focusing on incorporating 3D info to GraphGPT and scaling up the model size to improve the results in PCQM4M-v2. Now we achieved 0.0717 in the leaderboard, ranked after `EGT` and `UniMol+`.

Thank you.
